openapi: 3.0.1
info:
  title: Slack Plugin
  description: A plugin that allows the user to search for messages in Slack using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /search:
    post:
      operationId: searchSlack
      summary: Search for messages in Slack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The search query for Slack workspace
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchSlackResponse'

components:
  schemas:
    searchSlackResponse:
      type: array
      items:
        type: string
      description: The search results.
